apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: time
  name: deploy-time
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: time
  template:
    metadata:
      labels:
        app: time
    spec:
      containers:
        - name: time-container
          image: "058264152241.dkr.ecr.ap-northeast-2.amazonaws.com/juju:44808a11253842d4381b06d2927ab62b3de5a227"
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ap-northeast-2-ecr-registry-2
