apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: time
  name: deploy-time
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time
  template:
    metadata:
      labels:
        app: time
    spec:
      containers:
        - name: time-container
          image: 058264152241.dkr.ecr.ap-northeast-2.amazonaws.com/juju:ccb9d12dc980de6edb78b8416793ab48a0d626f7
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ap-northeast-2-ecr-registry-3
